### PR TITLE
extract system path helper fn

### PR DESCRIPTION
**Pull request by jbenden**
Extracts a helper function to deal with system paths; namely for Windows OS handling.

### CODE REVIEW

**Comment by dzid26** [comment]
All tools run ok for me now. 
Squiggles not showing as before.

**Comment by jbenden** [comment]
@dzid26 Do the error squiggles now appear?

**Comment by dzid26** [comment]
Oh, I forgot to test earlier. 
Unfortunately, squiggles still don't appear.

I wanted to investigate a bit, but couldn't bind breakpoints for some reason.

**Comment by jbenden** [comment]
Hi, I'll have to build a test VM running Windows, then. What clang/cppcheck/etc are you using? Is it choco or?

**Comment by dzid26** [comment]
Those:
- https://packages.msys2.org/package/clang ([MSYS](https://github.com/msys2/msys2-installer/releases/download/2022-10-28/msys2-x86_64-20221028.exe))
- [cppcheck](https://github.com/danmar/cppcheck/releases/download/2.9/cppcheck-2.9-x64-Setup.msi)

**Comment by jbenden** [comment]
Hi, I believe the squiggles problem to now be fixed. At least very hopeful! :)

FYI: The unit-tests fail to work at all on Windows; but [others are complaining](https://github.com/microsoft/vscode-test/issues/139). Maybe it'll be resolved at some point. The unit-tests do not even get a chance to run, it fails within early git/github extensions bundled with VSCode.

Thanks,
-Joe

**Comment by dzid26** [comment]
It worked this time. Great!

**Pull request merged**
